config/routes.rb
Rails.application.routes.draw do

  root 'top#index'
  get 'about' => 'top#about'
  resources :player
  resources :job

end

app/controllers/top_controller.rb
class TopController < ApplicationController
  def index
    @players = Player.all
    @players_count = Player.all.count
    @activities_count = Activity.all.count
    @ranking_vs_top10  = PlayerStatus.ranking_vs_top10
    @ranking_vs_higher = PlayerStatus.ranking_vs_higher
    @ranking_vs_lower  = PlayerStatus.ranking_vs_lower
    @ranking = Ranking.joins(:player).order("ranking asc").limit(30)
  end

  def about
  end
end

app/helpers/top_helper.rb
module TopHelper
end

app/views/top/_analysis_result.html.erb
<div class="col-md-4">
  <h2><%= title %></h2>
  <table class="table">
    <thead>
      <tr>
        <th>#</th>
        <th>Player</th>
        <th>W/L</th>
      </tr>
    </thead>
  <% result.each.with_index(1) do |r, n| %>
    <% 
      win  = eval("r.vs_#{name}_win")
      loss = eval("r.vs_#{name}_loss")
    %>
    <tbody>
      <tr>
        <td><%= n %></td>
        <td><%= r.player.name %></td>
        <td><%= link_to "#{win} / #{loss}", player_path(r.player.url_name) %></td>
      </tr>
    </tbody>
  <% end %>
  </table>
</div>

app/views/top/about.html.erb
<h1>About this site</h1>
<p>Comming Soon</p>

app/views/top/index.html.erb
<div class="app-description jumbotron">
  <h1>Analyze ATP tennis player activity</h1>
  <p class="lead">ATP Stat is an analytics service of atp tennis player activity.This service is using <a href=https://github.com/mosuke5/atp_scraper target="_blank">AtpScraper</a>.</p>
</div>

<h1 class="page-header">Current Data</h1>
<div class="row">
  <div class="col-md-4 current-data">
    <h2><%= @players_count %> <small>players</small></h2>
  </div>
  <div class="col-md-4 current-data">
    <h2><%= @activities_count %> <small>activities</small></h2>
  </div>
</div>
<h1 class="page-header">Analysis Data</h1>
<div class="row">
  <%= render 'analysis_result', { result: @ranking_vs_top10, title: 'vs Top10', name: 'top10' } %>
  <%= render 'analysis_result', { result: @ranking_vs_higher, title: 'vs Higher', name: 'higher' } %>
  <%= render 'analysis_result', { result: @ranking_vs_lower, title: 'vs Lower', name: 'lower' } %>
</div>
<h1 class="page-header">Current Ranking</h1>
<%= link_to "Show all players and search.", player_index_path %>
<div class="row">
  <% Range.new(0, 2).each do |n| %>
  <% start_ranking = n*10 %>
  <div class="col-md-4 current-ranking">
    <table class="table">
      <thead>
        <tr>
          <th>#</th>
          <th>Player</th>
          <th>Points</th>
        </tr>
      </thead>
      <tbody>
        <% @ranking[start_ranking,10].each do |r| %>
        <tr>
          <td><%= r.ranking %></td>
          <td><%= link_to r.name, player_path(r.player.url_name) %></td>
          <td><%= r.points %></td>
        </tr>
        <% end %>
      </tbody>
    </table>
  </div>
  <% end %>
</div>